## Names of ABX and AMR ##############################################
## Author: Steph Reynolds ######################################################
## Date Modified: 2022-03-30 ###################################################

# Convert ABX names to vector
names_abx <- "VANCOMYCIN|CEFTRIAXONE|CEFEPIME|LEVOFLOXACIN|CIPROFLOXACIN|AMIKACIN|GENTAMICIN|NEOMYCIN-POLYMYXIN|TOBRAMYCIN|ERTAPENEM|IMIPENEM-CILASTATIN|MEROPENEM|MEROPENEM-VABORBACTAM|CEFAZOLIN|CEFOXITIN|CEFOTETAN|CEFUROXIME|CEFTAZIDIME|CEFTAROLINE|TOBRAMYCIN|DALBAVANCIN|ORITAVANCIN|CLINDAMYCIN|DAPTOMYCIN|AZITHROMYCIN|ERYTHROMYCIN|AZTREONAM|LINEZOLID|AMPICILLIN|AMPICILLIN-SULBACTAM|NAFCILLIN|PENICILLIN|PIPERACILLIN-TAZOBACTAM|BACITRACIN|NEOMYCIN-POLYMYXIN|GENTAMICIN-POLYMYXIN|TRIMETHOPRIM-SULFAMETHOXAZOLE|SULFAMETHOXAZOLE-TRIMETHOPRIM|DOXYCYCLINE|MINOCYCLINE|CLOFAZIMINE|ISONIAZID|RIFAMPIN|TIGECYCLINE|TRIMETHOPRIM|AZTREONAM|GENTAMICIN|CEFTOLOZANE-TAZOBACTAM|CLINDAMYCIN|ALBAVANCIN|ERAVACYCLINE|GENTAMICIN-POLYMYXIN|CEFAZOLIN/CEFTAZIDIME|ORITAVANCIN|PENICILLIN|TEDIZOID|CEFIDEROCOL|COLISTIMETHATE"
#abx <- unlist(strsplit(names_abx, "\\|"))

# Convert AMR names to vector
names_amr <- "VANCOMYCIN|CEFTRIAXONE|CEFEPIME|LEVOFLOXACIN|CIPROFLOXACIN|AMIKACIN|GENTAMICIN|NEOMYCIN|POLYMYXIN|TOBRAMYCIN|ERTAPENEM|IMIPENEM|CILASTATIN|MEROPENEM|MEROPENEM|VABORBACTAM|CEFAZOLIN|CEFOXITIN|CEFOTETAN|CEFUROXIME|CEFTAZIDIME|CEFTAROLINE|TOBRAMYCIN|DALBAVANCIN|ORITAVANCIN|CLINDAMYCIN|DAPTOMYCIN|AZITHROMYCIN|ERYTHROMYCIN|AZTREONAM|LINEZOLID|AMPICILLIN|AMPICILLIN|SULBACTAM|NAFCILLIN|PENICILLIN|PIPERACILLIN|TAZOBACTAM|BACITRACIN|NEOMYCIN|POLYMYXIN|GENTAMICIN|POLYMYXIN|TRIMETHOPRIM|SULFAMETHOXAZOLE|SULFAMETHOXAZOLE|TRIMETHOPRIM|DOXYCYCLINE|MINOCYCLINE|CLOFAZIMINE|ISONIAZID|RIFAMPIN|TIGECYCLINE|TRIMETHOPRIM|AZTREONAM|GENTAMICIN|CEFTOLOZANE|TAZOBACTAM|CLINDAMYCIN|ALBAVANCIN|ERAVACYCLINE|GENTAMICIN|POLYMYXIN|CEFAZOLIN/CEFTAZIDIME|ORITAVANCIN|PENICILLIN|TEDIZOID|CEFIDEROCOL|COLISTIMETHATE|ACYCLOVIR|LETERMOVIR|GANCICLOVIR|ACYCLOVIR|CIDOFOVIR|FOSCARNET|REMDESIVIR|PERAMIVIR|CASPOFUNGIN|POSACONAZOLE|AMPHOTERICIN|ISAVUCONAZONIUM|MICAFUNGIN|VORICONAZOLE"
#amr <- unlist(strsplit(names_amr, "\\|"))
